apiVersion: v1
kind: Service
metadata:
  name: hello-world-1-svc
  namespace: test-env
spec:
  selector:
    app: nginx
    testService: service-1 
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081