- name: Set up Kubernetes monitoring
  become: false
  tags:
    - k8s_master
  block:
    - name: create monitoring namespace
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: monitoring
        definition:
          metadata:
            labels:
              istio-injection: enabled

    - name: Install grafana helm repo
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Copy grafana-values file
      tags: always
      become: no
      copy:
        src: grafana-values.yml
        dest: /home/server-admin/grafana-values.yml

    - name: Install chart
      kubernetes.core.helm:
        namespace: monitoring
        create_namespace: false
        release_name: loki
        chart_ref: grafana/loki-stack 
        values_files:
        - /home/server-admin/grafana-values.yml

    - name: Add service to make it accessible within the VPC
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: grafana-ui
            namespace: monitoring
            labels:
              name: grafana-ui
          spec:
            ports:
            - name: http
              port: 3000
              targetPort: 3000
              nodePort: 31300
            selector:
              app.kubernetes.io/name: grafana
            type: NodePort