- name: Set up Kubernetes vault
  become: false
  tags:
    - k8s_master
  block:
    - name: Create the vault k8s namespace
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: vault
        definition:
          metadata:
            labels:
              istio-injection: enabled
   
    - name: Setup TLS Lets Encrypt CA certificate
      tags: always
      become: yes
      copy:
        src: ~/{{ custom_domain }}.ca
        dest: "{{ key_location }}"

    - name: Setup TLS Lets Encrypt cert
      tags: always
      become: yes
      copy:
        src: ~/{{ custom_domain }}.crt
        dest: "{{ key_location }}"

    - name: Setup TLS Lets Encrypt key
      tags: always
      become: yes
      copy:
        src: ~/{{ custom_domain }}.key
        dest: "{{ key_location }}"

    - name: Check secret
      shell: kubectl get secrets -n vault -o json | grep vault-ha-tls
      register: secret
      ignore_errors: true

    - name: Create TLS secret from files
      command:
        cmd: |
          kubectl create secret generic vault-ha-tls
          -n vault
          --from-file=vault.key={{ key_location }}{{ custom_domain }}.key
          --from-file=vault.crt={{ key_location }}{{ custom_domain }}.crt
          --from-file=vault.ca={{ key_location }}{{ custom_domain }}.ca
      when: secret.stdout == ''

    - name: Install Vault repo
      kubernetes.core.helm_repository:
        name: hashicorp
        repo_url: https://helm.releases.hashicorp.com

    - name: Copy vault-values file
      tags: always
      become: no
      copy:
        src: vault-values.yml
        dest: /home/server-admin/vault-values.yml

    - name: Add custom domain
      replace:
        path: /home/server-admin/vault-values.yml
        regexp: custom_domain
        replace: "{{ custom_domain }}"

    - name: Install chart
      kubernetes.core.helm:
        namespace: vault
        create_namespace: true
        release_name: vault
        chart_ref: hashicorp/vault
        values_files:
        - /home/server-admin/vault-values.yml

    - name: Wait for unsealed vault
      tags: always
      pause:
        prompt: 'Join the Raft cluster and Unseal all instances of Vault, then press Enter'
