
- name: Set up base config for k8s master and node
  tags:
    - k8s_base
    - k8s_master
    - k8s_node
  block:
    - name: Disable SWAP K8S will not work with swap enabled (1/2)
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove SWAP from fstab K8S will not work with swap enabled (2/2)
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
      - swap
      - none

    - name: Get Kubernetes package key
      shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
      args:
        creates: "{{ k8s_gpgpath }}"

    - name: Install Kubernetes repository
      apt_repository:
        filename: kubernetes
        repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"

    - name: Install Dependencies
      package: name={{ item }} state=present force=yes install_recommends=no
      loop: "{{ k8s_dependencies }}"

    - name: Install Kubernetes Packages
      package: name={{ item }} state=present force=yes install_recommends=no
      loop: "{{ k8s_packages }}"

    - name: Install nfs
      package: name=nfs-common state=present force=yes install_recommends=no

