---

- hosts: k8s_master
  become: true
  roles:
    - docker
    - k8s_base
    - k8s_master
    - k8s_helm_charts

- hosts: k8s_node
  become: true
  roles:
    - docker
    - k8s_base
    - k8s_node
