apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-02T10:45:16Z"
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        rewrite stop {
          name regex input {1}.{2}.svc.cluster.local
          answer name (.*)\.(.*)\.svc\.cluster\.local  output
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
          reload
        loadbalance
    }
